function [MASS,STIFFNESS,nodes] = ReadPunchFile_nD(punchfile,dof)

%READUNCHFILE_ND Read Mass and Stiffness matrices from punch file generated by MSC Nastran.
%    [MASS,STIFFNESS,nodes] = ReadPunchFile_nD(punchfile,dof) reads data from a Nastran punch file
%    'punchfile' providing the MASS and STIFFNESS matrices on the degrees of freedom 'dof' ordered as the array 'nodes'
%    and for each node as ordered in 'dof'
%
%	 * IMPORTANT NOTE *
%	 Node numbers should be above 6 (1 from 6 reserved for degrees of freedom)
%
disp(['Reading Mass and Stiffness Matrices from file ' punchfile(1:find(punchfile=='.')-1)]);
% -------------------------------------------------------------------------
% FIND OUT THE START AND END OF THE MASS MATRIX SECTION
% -------------------------------------------------------------------------
file=textread(punchfile,'%s','delimiter','\n','whitespace','');
found_start = 0;
found_end = 0;
pos=0;
%
while found_start==0 || found_end==0,
    pos=pos+1;
    if file{pos}(1)=='D',
        if file{pos}(1:12)=='DMIG*   MAAX';
            % First row of Mass Matrix section starts with 'DMIG*   MAAX'
            if found_start==0,
                found_start=1;
                startline=pos;
            end
        end
        if file{pos}(1:12)=='DTI     TUG1';
            % First row AFTER Mass Matrix section starts with 'DMIG    VAX'
            found_end=1;
            endline=pos-1;
        end
    end
end

% READ OF THE MASS MATRIX SECTION
[col1,col2,col3,col4] = textread(punchfile,'%s%s%u%f',endline-startline+1,'delimiter',' ','headerlines',startline-1);
% For each data row and columns of the Mass Matrix are defined and stored
% into MASS
nodes_aux = col3(find(col3>6));
nodes = unique(nodes_aux);
Ndof = length(nodes)*length(dof);
MASS = zeros(Ndof,Ndof);
h1 = waitbar(0,'Reading mass matrix');
for p=1:length(col3),
   waitbar(p/length(col3),h1);
   if(ismember(col3(p),nodes)),

        % Start line for new node
        n=find(nodes==col3(p));
        row = length(dof)*(n-1)+find(dof==col4(p));
   else
        
        % Set of columns for previous node
        n=find(nodes==str2num(cell2mat(col2(p))));
        column = length(dof)*(n-1)+find(dof==col3(p));
        value=col4(p);
        MASS(row,column)=value;
        if row~=column,
            MASS(column,row)=value;
        end
   end
end
close(h1);
% FIND OUT THE START AND END OF THE STIFFNESS MATRIX SECTION
% -------------------------------------------------------------------------
file=textread(punchfile,'%s','delimiter','\n','whitespace','');
found_start = 0;
found_end = 0;
pos=0;
while found_start==0 || found_end==0,
    pos=pos+1;
    if file{pos}(1)=='D',
        if file{pos}(1:12)=='DMIG*   KAAX';
            % First row of Stiffness Matrix section starts with 'DMIG*   KAAX'
            if found_start==0,
                found_start=1;
                startline=pos;
            end
        end
        if file{pos}(1:12)=='DMIG    MAAX';
            % First row AFTER Stiffness Matrix section starts with 'DMIG    MAAX'
            found_end=1;
            endline=pos-1;
        end
    end
end
% READ OF THE STIFFNESS MATRIX FILE SECTION
[col1,col2,col3,col4] = textread(punchfile,'%s%s%u%f',endline-startline+1,'delimiter',' ','headerlines',startline-1);
% For each data row and columns of the Mass Matrix are defined and stored into STIFFNESS
STIFFNESS = zeros(Ndof,Ndof);
h2 = waitbar(0,'Reading stiffness matrix');
for p=1:length(col3),
   waitbar(p/length(col3),h2);
   if(ismember(col3(p),nodes)),

        % Start line for new node
        n=find(nodes==col3(p));
        row = length(dof)*(n-1)+find(dof==col4(p));
   else

        % Set of columns for previous node
        n=find(nodes==str2num(cell2mat(col2(p))));
        column = length(dof)*(n-1)+find(dof==col3(p));
        value=col4(p);
        STIFFNESS(row,column)=value;
        if row~=column,
            STIFFNESS(column,row)=value;
        end
   end
end
close(h2);